name: kydo
dependencies:
- click=6.6=py27_0
- db=5.3.28=1
- flask=0.11.1=py27_0
- itsdangerous=0.24=py27_0
- jinja2=2.8=py27_1
- markupsafe=0.23=py27_2
- openssl=1.0.2h=1
- pip=8.1.2=py27_0
- python=2.7.12=1
- readline=6.2=2
- requests=2.10.0=py27_0
- setuptools=23.0.0=py27_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- werkzeug=0.11.10=py27_0
- wheel=0.29.0=py27_0
- zlib=1.2.8=3
- pip:
  - backports.functools-lru-cache==1.2.1
  - cobe==2.1.2
  - inflect==0.2.5
  - irc==12.1.1
  - jaraco.classes==1.4
  - jaraco.collections==1.4
  - jaraco.functools==1.11
  - jaraco.itertools==1.7.1
  - jaraco.logging==1.5
  - jaraco.text==1.7
  - more-itertools==2.2
  - nltk==3.2.1
  - oauthlib==1.1.2
  - pystemmer==1.3.0
  - requests-oauthlib==0.6.2
  - six==1.10.0
  - tempora==1.4
  - tweepy==3.5.0

