name: kydo
dependencies:
- openssl=1.0.2h=1
- pip=8.1.2=py27_0
- python=2.7.12=1
- readline=6.2=2
- setuptools=23.0.0=py27_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py27_0
- zlib=1.2.8=3
- pip:
  - click==6.6
  - flask==0.11.1
  - flask-socketio==2.6.1
  - gevent==1.1.2
  - greenlet==0.4.10
  - itsdangerous==0.24
  - jinja2==2.8
  - markupsafe==0.23
  - nltk==3.2.1
  - oauthlib==1.1.2
  - python-engineio==0.9.2
  - python-socketio==1.4.4
  - requests==2.10.0
  - requests-oauthlib==0.6.2
  - six==1.10.0
  - tweepy==3.5.0
  - werkzeug==0.11.10

